"""Word (DOCX) ICD generator using python-docx.

Landscape so the full signal field set fits. Cover page, revision history,
interface overview, per-interface/packet signal tables (all registry columns),
and notes. The provenance stamp is written into the page footer.
"""
from __future__ import annotations

import os

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor, Inches

from .fields import SIGNAL_FIELDS
from .model import IcdModel
from .provenance import Provenance

_HEADER_BLUE = RGBColor(0x1F, 0x4E, 0x79)

# Full signal column set, sourced from the registry so the document can never
# silently omit a field. (label, attribute-name) in registry order.
_SIGNAL_COLS = [(f.label, f.name) for f in SIGNAL_FIELDS]


def _set_footer(section, prov: Provenance) -> None:
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = prov.footer_line()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in p.runs:
        run.font.size = Pt(7)
        run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)


def _shade_header_row(row) -> None:
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    for cell in row.cells:
        tcPr = cell._tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:fill"), "1F4E79")
        tcPr.append(shd)
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(7)


def _cell(value) -> str:
    """Render any field value into a document cell string (None -> blank)."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "Y" if value else "N"
    if isinstance(value, float):
        return str(int(value)) if value == int(value) else repr(value)
    return str(value)


def build_docx(model: IcdModel, prov: Provenance, path: str,
               base_dir: str | None = None) -> None:
    doc = Document()

    section = doc.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = section.page_height, section.page_width
    section.left_margin = Inches(0.5)
    section.right_margin = Inches(0.5)

    style = doc.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(10)

    meta = model.metadata

    # Per-revision auto-diff summaries (empty dict when no priorRevisions).
    rev_summaries = {}
    if model.prior_revisions:
        from .rev_summary import compute_revision_summaries
        bd = base_dir if base_dir is not None else os.getcwd()
        for rs in compute_revision_summaries(model, bd):
            rev_summaries[rs.revision] = rs.text

    # ---- Cover page ----
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("INTERFACE CONTROL DOCUMENT")
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = _HEADER_BLUE

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub.add_run(meta.document_title)
    r.font.size = Pt(16)

    for _ in range(2):
        doc.add_paragraph()

    cover_facts = [
        ("Document ID", meta.document_id),
        ("Program", meta.program),
        ("Revision", meta.revision),
        ("Revision Date", meta.revision_date),
        ("Author", meta.author),
        ("Input SHA-256", prov.input_hash),
        ("Generated By", f"{prov.tool_name} v{prov.tool_version}"),
    ]
    t = doc.add_table(rows=0, cols=2)
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for k, v in cover_facts:
        cells = t.add_row().cells
        kr = cells[0].paragraphs[0].add_run(k)
        kr.font.bold = True
        cells[1].paragraphs[0].add_run(str(v))

    doc.add_page_break()

    # ---- Revision history ----
    doc.add_heading("Revision History", level=1)
    rh = doc.add_table(rows=1, cols=5)
    rh.style = "Table Grid"
    hdr = rh.rows[0].cells
    for i, label in enumerate(["Revision", "Date", "Author", "Description",
                               "Changes in This Revision"]):
        hdr[i].paragraphs[0].add_run(label)
    _shade_header_row(rh.rows[0])
    for e in meta.revision_history:
        cells = rh.add_row().cells
        cells[0].text = e.revision
        cells[1].text = e.date
        cells[2].text = e.author
        cells[3].text = e.description
        cells[4].text = rev_summaries.get(e.revision, "")

    # ---- Interface overview ----
    doc.add_heading("Interface Overview", level=1)
    ov = doc.add_table(rows=1, cols=6)
    ov.style = "Table Grid"
    for i, label in enumerate(["ID", "Name", "Bus", "DAL", "Source", "Destination"]):
        ov.rows[0].cells[i].paragraphs[0].add_run(label)
    _shade_header_row(ov.rows[0])
    for iface in model.interfaces:
        cells = ov.add_row().cells
        cells[0].text = iface.id
        cells[1].text = iface.name
        cells[2].text = iface.bus_type
        cells[3].text = iface.dal
        cells[4].text = iface.source_lru
        cells[5].text = iface.destination_lru

    # ---- Per-interface / per-packet signal tables (FULL field set) ----
    doc.add_heading("Interface Definitions", level=1)
    for iface in model.interfaces:
        doc.add_heading(f"{iface.id} \u2014 {iface.name}", level=2)
        info = doc.add_paragraph()
        info.add_run(
            f"Bus: {iface.bus_type}   DAL: {iface.dal}   "
            f"{iface.source_lru} \u2192 {iface.destination_lru}   "
            f"Owning document: {iface.owning_document}"
        ).font.size = Pt(9)
        if iface.description:
            doc.add_paragraph(iface.description)

        for pkt in iface.packets:
            ph = doc.add_paragraph()
            pr = ph.add_run(f"Packet: {pkt.name}")
            pr.font.bold = True
            pr.font.size = Pt(10)
            if pkt.description:
                doc.add_paragraph(pkt.description).runs[0].font.size = Pt(9)

            tbl = doc.add_table(rows=1, cols=len(_SIGNAL_COLS))
            tbl.style = "Table Grid"
            for i, (label, _attr) in enumerate(_SIGNAL_COLS):
                tbl.rows[0].cells[i].paragraphs[0].add_run(label)
            _shade_header_row(tbl.rows[0])
            for sig in pkt.signals:
                cells = tbl.add_row().cells
                for i, (_label, attr) in enumerate(_SIGNAL_COLS):
                    cells[i].text = _cell(getattr(sig, attr))
                    for para in cells[i].paragraphs:
                        for run in para.runs:
                            run.font.size = Pt(7)

    # ---- Notes ----
    doc.add_heading("Notes", level=1)
    doc.add_paragraph(
        "1. This document is auto-generated from a schema-validated interface "
        "definition file. Do not edit this document directly; revise the "
        "source definition and regenerate.")
    doc.add_paragraph(
        f"2. Traceability anchor: input SHA-256 {prov.input_hash}.")
    doc.add_paragraph(
        "3. All signal ranges are expressed in the stated physical units "
        "prior to encoding/scaling unless otherwise noted.")

    for section in doc.sections:
        _set_footer(section, prov)

    import datetime
    epoch = datetime.datetime(2000, 1, 1, 0, 0, 0)
    doc.core_properties.created = epoch
    doc.core_properties.modified = epoch
    doc.core_properties.author = prov.tool_name

    doc.save(path)
    from .ooxml_determinism import normalize
    normalize(path)