"""PDF ICD generator using ReportLab (offline, no system browser needed).

Mirrors the DOCX structure. The provenance stamp is drawn on every page
footer via a page callback. ReportLab is preferred over WeasyPrint here
because it has no native HTML/CSS rendering dependencies, easing the offline
and PyInstaller packaging constraints.
"""
from __future__ import annotations

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from .model import IcdModel
from .provenance import Provenance

_BLUE = colors.HexColor("#1F4E79")
_SIGNAL_COLS = ["Signal", "Type", "Units", "Rate", "Min", "Max",
                "DBits", "XBits", "XByte", "Scale", "Description"]


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("CoverTitle", parent=ss["Title"],
                          textColor=_BLUE, fontSize=24, spaceAfter=18))
    ss.add(ParagraphStyle("Cell", parent=ss["Normal"], fontSize=7, leading=8))
    ss.add(ParagraphStyle("CellHdr", parent=ss["Normal"], fontSize=7,
                          leading=8, textColor=colors.white, fontName="Helvetica-Bold"))
    return ss


def _int(x):
    return "" if x is None else str(x)


def _fmt(x: float) -> str:
    if x == int(x):
        return str(int(x))
    return repr(x)


def build_pdf(model: IcdModel, prov: Provenance, path: str) -> None:
    # Determinism: ReportLab embeds a random document /ID and the current
    # timestamp by default. The 'invariant' global pins both to fixed values
    # so identical inputs yield byte-identical PDFs.
    from reportlab import rl_config
    rl_config.invariant = 1

    ss = _styles()
    meta = model.metadata

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColor(colors.HexColor("#606060"))
        canvas.drawCentredString(letter[0] / 2.0, 0.4 * inch, prov.footer_line())
        canvas.drawRightString(letter[0] - 0.6 * inch, 0.4 * inch,
                               f"Page {doc.page}")
        canvas.restoreState()

    doc = BaseDocTemplate(
        path, pagesize=letter,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        title=meta.document_title, author=prov.tool_name,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  doc.width, doc.height, id="main")
    doc.addPageTemplates([PageTemplate(id="all", frames=[frame], onPage=_footer)])

    story = []

    # ---- Cover ----
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("INTERFACE CONTROL DOCUMENT", ss["CoverTitle"]))
    story.append(Paragraph(meta.document_title, ss["Heading2"]))
    story.append(Spacer(1, 0.5 * inch))
    cover = [
        ["Document ID", meta.document_id],
        ["Program", meta.program],
        ["Revision", meta.revision],
        ["Revision Date", meta.revision_date],
        ["Author", meta.author],
        ["Input SHA-256", prov.input_hash],
        ["Generated By", f"{prov.tool_name} v{prov.tool_version}"],
    ]
    ct = Table(cover, colWidths=[1.6 * inch, 5.0 * inch])
    ct.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
    ]))
    story.append(ct)
    story.append(PageBreak())

    # ---- Revision history ----
    story.append(Paragraph("Revision History", ss["Heading1"]))
    rh = [["Revision", "Date", "Author", "Description"]]
    for e in meta.revision_history:
        rh.append([e.revision, e.date, e.author, Paragraph(e.description, ss["Cell"])])
    rht = Table(rh, colWidths=[0.9 * inch, 1.0 * inch, 1.3 * inch, 4.0 * inch],
                repeatRows=1)
    rht.setStyle(_grid_style())
    story.append(rht)
    story.append(Spacer(1, 0.3 * inch))

    # ---- Overview ----
    story.append(Paragraph("Interface Overview", ss["Heading1"]))
    ov = [["ID", "Name", "Bus", "DAL", "Source", "Destination"]]
    for iface in model.interfaces:
        ov.append([iface.id, Paragraph(iface.name, ss["Cell"]), iface.bus_type,
                   iface.dal, Paragraph(iface.source_lru, ss["Cell"]),
                   Paragraph(iface.destination_lru, ss["Cell"])])
    ovt = Table(ov, colWidths=[1.0 * inch, 1.8 * inch, 1.1 * inch, 0.5 * inch,
                               1.3 * inch, 1.5 * inch], repeatRows=1)
    ovt.setStyle(_grid_style())
    story.append(ovt)
    story.append(PageBreak())

    # ---- Per-interface signal tables ----
    story.append(Paragraph("Interface Definitions", ss["Heading1"]))
    for iface in model.interfaces:
        story.append(Paragraph(f"{iface.id} \u2014 {iface.name}", ss["Heading2"]))
        story.append(Paragraph(
            f"Bus: {iface.bus_type} &nbsp; DAL: {iface.dal} &nbsp; "
            f"{iface.source_lru} &rarr; {iface.destination_lru} &nbsp; "
            f"Owning document: {iface.owning_document}", ss["Cell"]))
        if iface.description:
            story.append(Paragraph(iface.description, ss["Normal"]))
        story.append(Spacer(1, 0.08 * inch))

        for pkt in iface.packets:
            label = f"Packet: {pkt.name}"
            if pkt.description:
                label += f" \u2014 {pkt.description}"
            story.append(Paragraph(label, ss["Heading2"]))
            rows = [[Paragraph(c, ss["CellHdr"]) for c in _SIGNAL_COLS]]
            for sig in pkt.signals:
                rows.append([
                    Paragraph(sig.name, ss["Cell"]),
                    Paragraph(sig.signal_type, ss["Cell"]),
                    Paragraph(sig.units or "", ss["Cell"]),
                    Paragraph(_fmt(sig.update_rate_hz), ss["Cell"]),
                    Paragraph(_fmt(sig.range_min), ss["Cell"]),
                    Paragraph(_fmt(sig.range_max), ss["Cell"]),
                    Paragraph(_int(sig.data_bits), ss["Cell"]),
                    Paragraph(_int(sig.xmit_bits), ss["Cell"]),
                    Paragraph(_int(sig.xmit_bytes), ss["Cell"]),
                    Paragraph(_fmt(sig.scaling), ss["Cell"]),
                    Paragraph(sig.description or "", ss["Cell"]),
                ])
            col_w = [0.9, 0.6, 0.55, 0.45, 0.5, 0.5, 0.45, 0.45, 0.45, 0.45, 1.35]
            t = Table(rows, colWidths=[w * inch for w in col_w], repeatRows=1)
            t.setStyle(_grid_style())
            story.append(t)
            story.append(Spacer(1, 0.16 * inch))

    # ---- Notes ----
    story.append(Paragraph("Notes", ss["Heading1"]))
    for note in [
        "1. This document is auto-generated from a schema-validated interface "
        "definition file. Do not edit directly; revise the source and regenerate.",
        f"2. Traceability anchor: input SHA-256 {prov.input_hash}.",
        "3. Signal ranges are in stated physical units prior to encoding/scaling "
        "unless otherwise noted.",
    ]:
        story.append(Paragraph(note, ss["Normal"]))
        story.append(Spacer(1, 0.05 * inch))

    doc.build(story)


def _grid_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#999999")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F6FB")]),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ])
