"""Word (DOCX) ICD generator using python-docx.

Follows a standard aviation ICD structure: cover page, revision history,
interface overview, per-interface signal tables, and notes. The provenance
stamp is written into the page footer for tool-qualification evidence.
"""
from __future__ import annotations

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from .model import IcdModel
from .provenance import Provenance

_HEADER_BLUE = RGBColor(0x1F, 0x4E, 0x79)
_SIGNAL_COLS = ["Signal", "Type", "Dir", "Units", "Min", "Max",
                "Rate (Hz)", "Scale", "Opt", "Description"]


def _set_footer(section, prov: Provenance) -> None:
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = prov.footer_line()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in p.runs:
        run.font.size = Pt(7)
        run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)


def _shade_header_row(row) -> None:
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    for cell in row.cells:
        tcPr = cell._tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:fill"), "1F4E79")
        tcPr.append(shd)
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(8)


def build_docx(model: IcdModel, prov: Provenance, path: str) -> None:
    doc = Document()

    # Base font.
    style = doc.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(10)

    meta = model.metadata

    # ---- Cover page ----
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("INTERFACE CONTROL DOCUMENT")
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = _HEADER_BLUE

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub.add_run(meta.document_title)
    r.font.size = Pt(16)

    for _ in range(2):
        doc.add_paragraph()

    cover_facts = [
        ("Document ID", meta.document_id),
        ("Program", meta.program),
        ("Revision", meta.revision),
        ("Revision Date", meta.revision_date),
        ("Author", meta.author),
        ("Input SHA-256", prov.input_hash),
        ("Generated By", f"{prov.tool_name} v{prov.tool_version}"),
    ]
    t = doc.add_table(rows=0, cols=2)
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for k, v in cover_facts:
        cells = t.add_row().cells
        kr = cells[0].paragraphs[0].add_run(k)
        kr.font.bold = True
        cells[1].paragraphs[0].add_run(str(v))

    doc.add_page_break()

    # ---- Revision history ----
    doc.add_heading("Revision History", level=1)
    rh = doc.add_table(rows=1, cols=4)
    rh.style = "Table Grid"
    hdr = rh.rows[0].cells
    for i, label in enumerate(["Revision", "Date", "Author", "Description"]):
        hdr[i].paragraphs[0].add_run(label)
    _shade_header_row(rh.rows[0])
    for e in meta.revision_history:
        cells = rh.add_row().cells
        cells[0].text = e.revision
        cells[1].text = e.date
        cells[2].text = e.author
        cells[3].text = e.description

    # ---- Interface overview ----
    doc.add_heading("Interface Overview", level=1)
    ov = doc.add_table(rows=1, cols=6)
    ov.style = "Table Grid"
    for i, label in enumerate(["ID", "Name", "Bus", "DAL", "Source", "Destination"]):
        ov.rows[0].cells[i].paragraphs[0].add_run(label)
    _shade_header_row(ov.rows[0])
    for iface in model.interfaces:
        cells = ov.add_row().cells
        cells[0].text = iface.id
        cells[1].text = iface.name
        cells[2].text = iface.bus_type
        cells[3].text = iface.dal
        cells[4].text = iface.source_lru
        cells[5].text = iface.destination_lru

    # ---- Per-interface signal tables ----
    doc.add_heading("Interface Definitions", level=1)
    for iface in model.interfaces:
        doc.add_heading(f"{iface.id} \u2014 {iface.name}", level=2)
        info = doc.add_paragraph()
        info.add_run(
            f"Bus: {iface.bus_type}   DAL: {iface.dal}   "
            f"{iface.source_lru} \u2192 {iface.destination_lru}   "
            f"Owning document: {iface.owning_document}"
        ).font.size = Pt(9)
        if iface.description:
            doc.add_paragraph(iface.description)

        tbl = doc.add_table(rows=1, cols=len(_SIGNAL_COLS))
        tbl.style = "Table Grid"
        for i, label in enumerate(_SIGNAL_COLS):
            tbl.rows[0].cells[i].paragraphs[0].add_run(label)
        _shade_header_row(tbl.rows[0])
        for sig in iface.signals:
            cells = tbl.add_row().cells
            vals = [
                sig.name, sig.data_type, sig.direction, sig.units or "",
                _fmt(sig.range_min), _fmt(sig.range_max),
                _fmt(sig.update_rate_hz), _fmt(sig.scaling),
                "Y" if sig.optional else "N", sig.description or "",
            ]
            for i, val in enumerate(vals):
                cells[i].text = val
                for para in cells[i].paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(8)

    # ---- Notes ----
    doc.add_heading("Notes", level=1)
    doc.add_paragraph(
        "1. This document is auto-generated from a schema-validated interface "
        "definition file. Do not edit this document directly; revise the "
        "source definition and regenerate.")
    doc.add_paragraph(
        f"2. Traceability anchor: input SHA-256 {prov.input_hash}.")
    doc.add_paragraph(
        "3. All signal ranges are expressed in the stated physical units "
        "prior to encoding/scaling unless otherwise noted.")

    # Footer on every section.
    for section in doc.sections:
        _set_footer(section, prov)
    # Pin core-properties timestamps to a fixed epoch for determinism.
    import datetime
    epoch = datetime.datetime(2000, 1, 1, 0, 0, 0)
    doc.core_properties.created = epoch
    doc.core_properties.modified = epoch
    doc.core_properties.author = prov.tool_name

    doc.save(path)
    from .ooxml_determinism import normalize
    normalize(path)


def _fmt(x: float) -> str:
    # Stable numeric formatting: integers without trailing .0.
    if x == int(x):
        return str(int(x))
    return repr(x)
