"""Standalone PDF diff report (ReportLab, offline, deterministic).

Renders a DiffResult (from `diff.diff`) into a formatted PDF change report:
a header with both input SHA-256 hashes and a change summary, then ADDED /
REMOVED / MODIFIED sections. This is the two-file "Compare Revisions" download;
it is intentionally separate from the per-revision summary column embedded in
the ICD document (that lives in gen_docx/gen_pdf via rev_summary).

Determinism: identical inputs -> byte-identical PDF (rl_config.invariant).
"""
from __future__ import annotations

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph, Spacer,
    Table, TableStyle,
)

from .diff import DiffResult
from .provenance import TOOL_NAME, TOOL_VERSION

_BLUE = colors.HexColor("#1F4E79")
_GREEN = colors.HexColor("#1E7A46")
_RED = colors.HexColor("#9E2B2B")
_VIOLET = colors.HexColor("#5B4B9E")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("DiffTitle", parent=ss["Title"], textColor=_BLUE,
                          fontSize=22, spaceAfter=14))
    ss.add(ParagraphStyle("Sec", parent=ss["Heading2"], fontSize=13,
                          spaceBefore=12, spaceAfter=6))
    ss.add(ParagraphStyle("Cell", parent=ss["Normal"], fontSize=8, leading=10))
    ss.add(ParagraphStyle("CellHdr", parent=ss["Normal"], fontSize=8, leading=10,
                          textColor=colors.white, fontName="Helvetica-Bold"))
    return ss


def _grid(header_color):
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#999999")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#F2F6FB")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ])


def build_diff_pdf(res: DiffResult, old_hash: str, new_hash: str, path: str,
                   old_label: str = "Previous revision",
                   new_label: str = "New revision") -> None:
    from reportlab import rl_config
    rl_config.invariant = 1

    ss = _styles()

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColor(colors.HexColor("#606060"))
        canvas.drawCentredString(
            letter[0] / 2.0, 0.4 * inch,
            f"Generated by {TOOL_NAME} v{TOOL_VERSION} | ICD change report")
        canvas.drawRightString(letter[0] - 0.6 * inch, 0.4 * inch,
                               f"Page {doc.page}")
        canvas.restoreState()

    doc = BaseDocTemplate(
        path, pagesize=letter,
        leftMargin=0.7 * inch, rightMargin=0.7 * inch,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        title="ICD Change Report", author=TOOL_NAME)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height,
                  id="main")
    doc.addPageTemplates([PageTemplate(id="all", frames=[frame], onPage=_footer)])

    story = []
    story.append(Paragraph("ICD CHANGE REPORT", ss["DiffTitle"]))

    # ---- Provenance / summary block ----
    n_added = len(res.added_interfaces) + len(res.added_signals)
    n_removed = len(res.removed_interfaces) + len(res.removed_signals)
    n_mod = len(res.modified_signals)
    facts = [
        ["Compared", f"{old_label}  \u2192  {new_label}"],
        ["Previous input SHA-256", old_hash],
        ["New input SHA-256", new_hash],
        ["Summary", f"{n_added} added \u00b7 {n_removed} removed \u00b7 "
                    f"{n_mod} modified"],
    ]
    ft = Table(facts, colWidths=[1.8 * inch, 5.0 * inch])
    ft.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
    ]))
    story.append(ft)
    story.append(Spacer(1, 0.2 * inch))

    if not res.has_changes:
        story.append(Paragraph("No differences detected.", ss["Normal"]))
        doc.build(story)
        return

    # ---- Interfaces added/removed ----
    if res.added_interfaces or res.removed_interfaces:
        story.append(Paragraph("Interface Changes", ss["Sec"]))
        rows = [["Change", "Interface ID"]]
        for i in res.added_interfaces:
            rows.append(["ADDED", i])
        for i in res.removed_interfaces:
            rows.append(["REMOVED", i])
        t = Table(rows, colWidths=[1.2 * inch, 5.6 * inch], repeatRows=1)
        t.setStyle(_grid(_BLUE))
        story.append(t)

    # ---- Added signals ----
    if res.added_signals:
        story.append(Paragraph(f"Added Signals ({len(res.added_signals)})",
                               ss["Sec"]))
        rows = [[Paragraph("Interface", ss["CellHdr"]),
                 Paragraph("Packet", ss["CellHdr"]),
                 Paragraph("Signal", ss["CellHdr"])]]
        for iid, pkt, s in res.added_signals:
            rows.append([Paragraph(iid, ss["Cell"]), Paragraph(pkt, ss["Cell"]),
                         Paragraph(s, ss["Cell"])])
        t = Table(rows, colWidths=[2.4 * inch, 2.0 * inch, 2.4 * inch],
                  repeatRows=1)
        t.setStyle(_grid(_GREEN))
        story.append(t)

    # ---- Removed signals ----
    if res.removed_signals:
        story.append(Paragraph(f"Removed Signals ({len(res.removed_signals)})",
                               ss["Sec"]))
        rows = [[Paragraph("Interface", ss["CellHdr"]),
                 Paragraph("Packet", ss["CellHdr"]),
                 Paragraph("Signal", ss["CellHdr"])]]
        for iid, pkt, s in res.removed_signals:
            rows.append([Paragraph(iid, ss["Cell"]), Paragraph(pkt, ss["Cell"]),
                         Paragraph(s, ss["Cell"])])
        t = Table(rows, colWidths=[2.4 * inch, 2.0 * inch, 2.4 * inch],
                  repeatRows=1)
        t.setStyle(_grid(_RED))
        story.append(t)

    # ---- Modified signals ----
    if res.modified_signals:
        story.append(Paragraph(f"Modified Signals ({len(res.modified_signals)})",
                               ss["Sec"]))
        rows = [[Paragraph("Signal", ss["CellHdr"]),
                 Paragraph("Field", ss["CellHdr"]),
                 Paragraph("Old", ss["CellHdr"]),
                 Paragraph("New", ss["CellHdr"])]]
        for sc in res.modified_signals:
            sig_id = f"{sc.interface_id}/{sc.packet_name}.{sc.signal_name}"
            for j, ch in enumerate(sc.changes):
                rows.append([
                    Paragraph(sig_id if j == 0 else "", ss["Cell"]),
                    Paragraph(ch.field, ss["Cell"]),
                    Paragraph("" if ch.old is None else str(ch.old), ss["Cell"]),
                    Paragraph("" if ch.new is None else str(ch.new), ss["Cell"]),
                ])
        t = Table(rows, colWidths=[2.9 * inch, 1.3 * inch, 1.3 * inch,
                                   1.3 * inch], repeatRows=1)
        t.setStyle(_grid(_VIOLET))
        story.append(t)

    doc.build(story)
