"""Provenance stamp shared by every generated artifact.

For DO-330 tool-qualification evidence each output must declare:
  * the tool name and version,
  * the SHA-256 of the exact input file,
  * the input schema version.

Determinism note: the stamp intentionally contains NO timestamp or hostname.
Identical inputs must yield byte-identical outputs. Run time is recorded only
in the separate run log, never embedded in artifacts.
"""
from __future__ import annotations

from dataclasses import dataclass

TOOL_NAME = "icdgen"
TOOL_VERSION = "1.0.0"


@dataclass(frozen=True)
class Provenance:
    tool_name: str
    tool_version: str
    input_hash: str
    schema_version: str

    @classmethod
    def create(cls, input_hash: str, schema_version: str) -> "Provenance":
        return cls(TOOL_NAME, TOOL_VERSION, input_hash, schema_version)

    @property
    def short_hash(self) -> str:
        return self.input_hash[:16]

    def footer_line(self) -> str:
        return (f"Generated by {self.tool_name} v{self.tool_version} | "
                f"schema {self.schema_version} | "
                f"input SHA-256 {self.short_hash}")

    def banner_lines(self) -> list[str]:
        """Comment banner for source-code artifacts."""
        return [
            f"{self.tool_name} v{self.tool_version}",
            f"Schema version: {self.schema_version}",
            f"Input SHA-256:  {self.input_hash}",
            "DO NOT EDIT - regenerate from the source ICD definition.",
        ]
